project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Matthew Weirick Johnson"
  site-url: https://mattweirick.com/test
    left:
      - href: research/index.qmd
        text: Research
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source
